default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: doubleup_development
  <% if RUBY_PLATFORM =~ /darwin/ %>gssencmode: disable<% end %>

test:
  <<: *default
  database: doubleup_test
  <% if RUBY_PLATFORM =~ /darwin/ %>gssencmode: disable<% end %>

production:
  <<: *default
  database: doubleup_production

