default: &default
  rotating_brunch:
    active: true
    channel: rotating-brunch
    schedule: fortnightly
    size: 4

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

