default: &default
  coffee_time:
    active_in: all
    slack_channel: rotating-coffee-time
    schedule: weekly
    target_size: 2
  q_branch:
    active_in: all
    slack_channel: rotating-q-branch
    schedule: monthly
    target_size: 2
  quest:
    active_in:
      - development
    slack_channel: rotating-quest
    schedule: monthly
    target_size:
      strategy: exact_size
      size: 2
    protractable: true
  rotating_brunch:
    active_in: all
    slack_channel: rotating-brunch
    schedule: fortnightly
    target_size: 4

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
